version: "3.8"

services:
  api:
    image: registry.gitlab.com/dewadg/twtx
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == worker
      labels:
        - traefik.http.routers.twtx.rule=Host(`twtx.dewadg.id`)
        - traefik.http.routers.twtx.tls=true
        - traefik.http.routers.twtx.tls.certresolver=letsencrypt
        - traefik.http.services.twtx.loadbalancer.server.port=8000
        - traefik.docker.network=cb
    env_file:
      - ${CB_STACK}.env

networks:
  default:
    external: true
    name: cb
